"""
Hydrogel book‑probe strategy for data collection.

This file implements a Trader class that does not attempt to trade
profitably.  Instead, it logs key features of the order book and
midpoint at each iteration.  You can use it to gain insight into
bot behaviour and product dynamics for Hydrogel.  Metrics logged
include:

* Timestamp
* Best bid and ask prices with corresponding volumes
* Spread and midpoint
* Order‑book imbalance (OBI) at the top price level and summed over
  the top five price levels on each side

The algorithm returns no orders, so it will not trade or take on
positions.  Use the logs generated by the platform to analyse the
printed information and develop better strategies.
"""

from datamodel import OrderDepth, TradingState, Order
from typing import Dict, List, Tuple
import jsonpickle


class Trader:
    def run(self, state: TradingState) -> Tuple[Dict[str, List[Order]], int, str]:
        product = "HYDROGEL_PACK"
        # No orders will be placed
        orders: Dict[str, List[Order]] = {product: []}
        conversions = 0

        # Gather order book information
        depth: OrderDepth = state.order_depths.get(product)
        if depth:
            # Extract best bid/ask and volumes
            best_bid = max(depth.buy_orders.keys()) if depth.buy_orders else None
            best_ask = min(depth.sell_orders.keys()) if depth.sell_orders else None
            bid_vol = depth.buy_orders[best_bid] if best_bid is not None else 0
            ask_vol = -depth.sell_orders[best_ask] if best_ask is not None else 0

            # Compute mid and spread
            if best_bid is not None and best_ask is not None:
                mid = (best_bid + best_ask) // 2
                spread = best_ask - best_bid
            elif best_bid is not None:
                mid = best_bid
                spread = 0
            elif best_ask is not None:
                mid = best_ask
                spread = 0
            else:
                mid = 0
                spread = 0

            # Compute top‑level OBI
            total_vol_top = bid_vol + ask_vol
            if total_vol_top != 0:
                obi_top = (bid_vol - ask_vol) / total_vol_top
            else:
                obi_top = 0.0

            # Depth‑weighted OBI using top 5 levels
            obi_depth = 0.0
            bid_sum = 0
            ask_sum = 0
            # Sum volumes for the top 5 price levels on each side
            if depth.buy_orders:
                for price in sorted(depth.buy_orders.keys(), reverse=True)[:5]:
                    bid_sum += depth.buy_orders[price]
            if depth.sell_orders:
                for price in sorted(depth.sell_orders.keys())[:5]:
                    ask_sum += -depth.sell_orders[price]
            total_sum = bid_sum + ask_sum
            if total_sum != 0:
                obi_depth = (bid_sum - ask_sum) / total_sum

            # Print metrics
            print(f"TS={state.timestamp} BID={best_bid}:{bid_vol} ASK={best_ask}:{ask_vol} MID={mid} SPREAD={spread} OBI_top={obi_top:.3f} OBI_depth={obi_depth:.3f}")

        # Persist no state
        trader_data = ""
        return orders, conversions, trader_data